name: Closed Pull Request

on:
  pull_request:
    types: [closed]

jobs:
  get_pull_request_body:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get pull request body
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          NUMBER=$(echo $GITHUB_REF | sed -e 's/[^0-9]//g')
          echo $NUMBER
