name: Get Branch Names

on:
  pull_request:
    types: [opened]

jobs:
  get_branch_names:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Branch Names
        id: get_branch_names
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch -p
          branch_names=$(
            git branch -r | grep feature | tr -d ' ' | sed -e s/origin\\///g | tr '\n' ','
          )
          echo "branch_names=${branch_names}" >> $GITHUB_OUTPUT
      - name: Echo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          branchNames=${{ steps.get_branch_names.outputs.branch_names }}
          branchNameArr=(${branchNames//,/ })
          for branchName in "${branchNameArr[@]}"; do
            echo $branchName
          done
          gh pr create -B ${branchNameArr[0]} -H master -t 'test' -b ''
    
