name: Get Branch Names

on:
  pull_request:
    types: [opened]

jobs:
  get_branch_names:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Branch Names
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          branch_names=$(
            git branch -r
          )
          echo "BRANCH_NAMES=${branch_names}" >> $GITHUB_ENV
      - name: Echo
        run: echo $env.BRANCH_NAMES
    
